### ISSUE TITLE
Heyo, please add a package

### ISSUE THREAD

**Issue by ZenRepublic** [solana-playground/solana-playground#100]
import { Metadata } from "@metaplex-foundation/mpl-token-metadata";

this one please hihi :>

**Comment by acheroncrypto** [comment]
Hey you can actually use this in playground: `import { Metadata } from "@metaplex-foundation/js";`.

The one problem with Metaplex is that their codebase is so big that it slows down type hints quite a bit, so the type hints are disabled for `@metaplex-foundation/js` for now.

**Comment by jim4067** [comment]
Hello @acheroncrypto 👋🏾 ,

What about the methods in the `@metaplex-foundation/mpl-token-metadata` packages?

This is what I am trying to do. 

```ts
import {
  MasterEdition,
  Metadata
} from "@metaplex-foundation/mpl-token-metadata";
```

**Comment by acheroncrypto** [comment]
> Hello @acheroncrypto 👋🏾 ,
> 
> What about the methods in the `@metaplex-foundation/mpl-token-metadata` package?
> 
> This is what I am trying to do.
> 
> ```ts
> import {
>   MasterEdition,
>   Metadata
> } from "@metaplex-foundation/mpl-token-metadata";
> ```

`@metaplex-foundation/mpl-token-metadata` is not currently available but the issue with slow types has been resolved so we should be able to support it as well.

**Comment by acheroncrypto** [comment]
Added `@metaplex-foundation/mpl-token-metadata` package in https://github.com/solana-playground/solana-playground/commit/eddb21734d5bddda4c868abe3eea8c862150fbff. https://github.com/solana-playground/solana-playground/blob/df195c4a38cf8a161c4f3896e4c33afb0f487b19/supported-packages.json#L16
