### ISSUE TITLE
Can you add a crate for generating random numbers?

### ISSUE THREAD

**Issue by Kuldotha** [solana-playground/solana-playground#107]
Preferably rand! Thanks :)

**Comment by acheroncrypto** [comment]
`rand` is not available for on-chain programs([restrictions](https://docs.solana.com/developing/on-chain-programs/developing-rust#restrictions)), however you can now use [switchboard-v2](https://docs.rs/switchboard-v2/0.1.20/switchboard_v2/) crate in Solana Playground for this purpose. Learn more from [switchboard-docs](https://docs.switchboard.xyz/).
