### ISSUE TITLE
Problem with wasm-client

### ISSUE THREAD

**Issue by davidlampach** [solana-playground/solana-playground#110]
I am attempting to implement the wasm-client.  The example code provided does not work.  I can create the client, and make a new keypair, but when I go to check the balance, I run into issues with calling async functions.  Once I start with async functions in Rust, it seems like I get dragged back in to using tokio, but tokio is not wasm compatible.  

Do the examples work for you as written?  How do you deal with the async aspects of get_balance and wasm?

**Comment by acheroncrypto** [comment]
You are right that `tokio` doesn't have support for wasm, however you can create async wasm functions with `#[wasm_bindgen]` macro:
```rs
#[wasm_bindgen]
pub async fn main() {...}
```

There are more ways to create async wasm functions but `wasm-bindgen` is the most accesible option.

**Comment by davidlampach** [comment]
Thanks for responding.  I have crafted the following monstrosity.  I can't get anything inside the get_balance function to run.  I've been messing around with many permutations of configurations, so this is one that compiles and runs everything except the get_balance function.  Any thoughts why none of it is running?   btw, I can get all of this functionality to work in a non-wasm environment using the rpc client, so I figure it should work with this library in wasm.


#[wasm_bindgen(start)]
pub async fn main_js()  {
// Create client
let client = WasmClient::new("http://127.0.0.1:8899");

// Get a random pubkey
let pubkey = Keypair::new().pubkey();

async {
get_balances(client, &pubkey);
};

console::log_1(&"Outside Function".into());
console::log_1(&pubkey.into());

pub async fn get_balances(client : WasmClient, pubkey : &Pubkey) -> ClientResult<u64> { 

    console::log_1(&"Inside Function".into());

    let balance = client.get_balance(pubkey).await?; // in lamports
    console::log_1(&"Inside Function".into());

    Ok(balance)

    }
}

**Comment by davidlampach** [comment]
I got it working with  the following code, which may have some superfluous stuff:
I added an airdrop call to test another functions functionality.  It all works.


use solana_client_wasm::{
    solana_sdk::signature::{Keypair, Signer},
    WasmClient,
};

use solana_sdk::pubkey::Pubkey;
use web_sys::console;
use wasm_bindgen_macro::wasm_bindgen;
use std::str::FromStr;


#[wasm_bindgen(start)]
pub async fn main_js()  {

let client = WasmClient::new("http://127.0.0.1:8899");

let pubkey = Pubkey::from_str("5zG5Ssh7swZf5TqvL2ZbrU95mAvqsa19GcZPfKg5oiVk").unwrap();


client.request_airdrop(&pubkey, 5000).await.unwrap();
let balance = client.get_balance(&pubkey).await.unwrap(); // in lamports

console::log_1(&"View me in browser console".into());

console::log_1(&balance.into());  //this is the balance

}

**Comment by acheroncrypto** [comment]
Great! [solana-wasm-client](https://github.com/solana-playground/solana-playground/tree/master/wasm/solana-client) is being used in [solana-cli-wasm](https://github.com/solana-playground/solana-playground/tree/master/wasm/solana-cli) and [spl-token-cli-wasm](https://github.com/solana-playground/solana-playground/tree/master/wasm/spl-token-cli), and all rpc methods have been tested.

I'm closing this now since it's solved but feel free to open another issue if you run into any problems.
