### ISSUE TITLE
Full crate upgrade

### ISSUE THREAD

**Issue by GageBachik** [solana-playground/solana-playground#114]
Hey, I'm doing some tutorials around the new programmable NFT standard. This website has come a long way since it was first created and I think it's quite honestly an amazing resource for onboarding new Solana devs.

I'd like to use it in my tutorials, but the mpl-token-metadata crate is outdated and doesn't have the new standard functions.
Since create_metadata_v3 and master edition are being deprecated now might be a good time to just update all the crates to the latest ones 💪 

I tried to do it for you but couldn't find where you guys are pulling these crates in from.
All the Solana SDKs 1.15.0 etc updated without issue though.

**Comment by acheroncrypto** [comment]
Hey, thank you for the kind words! The crates currently don't live in the repository but I've just updated `mpl-token-metadata` crate to the [latest](https://docs.rs/mpl-token-metadata/1.8.3/mpl_token_metadata/) version. Let me know if this works for you.

**Comment by GageBachik** [comment]
Yes thanks a ton ❤️
