### ISSUE TITLE
The correct way to serialize the SystemInstruction transfer payload with borsh

### ISSUE THREAD

**Issue by iMrDJAi** [solana-playground/solana-playground#120]
On client side, trying to serialize a payload, followed [this tutorial](https://solanacookbook.com/guides/serialization.html#how-to-serialize-instruction-data-on-the-client), here is my code:

```ts
// Our instruction payload vocabulary
class Payload {
  id: number
  key: string
  value?: string
  constructor({
    id, key, value
  } : {
    id: number, key: string, value?: string
  }) {
    this.id = id
    this.key = key
    this.value = value
  }
}

// Borsh needs a schema describing the payload
const payloadSchema = new Map([
  [
    Payload,
    {
      kind: 'struct',
      fields: [
        ['id', 'u8'],
        ['key', 'string'],
        ['value', ['option', 'string']]
      ]
    }
  ]
])

const transfer = new Payload({
  id: 2,
  key: (web3.LAMPORTS_PER_SOL * 0.42).toFixed()
})

const data = Buffer.from(borsh.serialize(payloadSchema, transfer))
```

Getting this error: `Uncaught error: Cannot read properties of undefined (reading 'borshSerialize')`

Removing `['value', ['option', 'string']]` worked, but it also produced an invalid buffer, leading to that error: `Uncaught error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: invalid instruction data`.

For reference, here is how `data` looks like: `<Buffer 02 09 00 00 00 34 32 30 30 30 30 30 30 30>`.
And this is a how a valid buffer looks like:   `<Buffer 02 00 00 00 00 b1 08 19 00 00 00 00>`.

Not sure what's the issue, but I think that `borsh` that ships with the playground is broken.

**Comment by katopz** [comment]
I spot that `option` look like [this](https://github.com/near/borsh-js/blob/6db74764cedb88097bd6d5636407f0b3481fba4c/borsh-ts/test/fuzz/transaction-example/transaction.js#L158) , so maybe this should work?
```ts
['value', { kind: 'option', type: 'string' }],
```
Never use `borsh` in `js` before so I could be wrong.

**Comment by acheroncrypto** [comment]
Thanks @katopz, that's the correct way of using the `Option` type.

> For reference, here is how data looks like: <Buffer 02 09 00 00 00 34 32 30 30 30 30 30 30 30>.
And this is a how a valid buffer looks like: <Buffer 02 00 00 00 00 b1 08 19 00 00 00 00>.

The first buffer is the correct one though.
`u8` -> 1 byte(first byte **02**)
`String` -> 4 bytes for size and 1 byte per UTF-8 character(`09 00 00 00` for size and `34 32 30 30 30 30 30 30 30` for the content)

Additionally if you add the `Option` type as @katopz mentioned, `None` will add 1 byte as `00`.

**Comment by iMrDJAi** [comment]
@katopz `['value', { kind: 'option', type: 'string' }]` worked! But I'm still getting `Uncaught error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: invalid instruction data` though.

@acheroncrypto The second buffer is valid, it's produced by the `SystemProgram` class:
```ts
const transactionData = web3.SystemProgram.transfer({
  fromPubkey: senderKeypair.publicKey,
  toPubkey: recipientAddress,
  lamports: parseInt(`${web3.LAMPORTS_PER_SOL * 0.42}`)
})
console.log(transactionData.data) // <Buffer 02 00 00 00 00 b1 08 19 00 00 00 00>
```

**Comment by katopz** [comment]
1. I didn't see whole code so I'm not sure your `recipientAddress` type is `PublicKey` or not?
2. Maybe use `lamports: 10,` to ensure no something wrong with `parseInt`, just in case.
3. I'm not sure what your expect so maybe try take a look at test cases that suite your need [here](https://github.com/solana-labs/solana-web3.js/blob/87d33ac68e2453b8a01cf8c425aa7623888434e8/packages/library-legacy/test/transaction.test.ts#L358-L377)
```ts
 it('getEstimatedFee', async () => {
      const connection = new Connection(url);
      const accountFrom = Keypair.generate();
      const accountTo = Keypair.generate();

      const latestBlockhash = await helpers.latestBlockhash({connection});

      const transaction = new Transaction({
        feePayer: accountFrom.publicKey,
        ...latestBlockhash,
      }).add(
        SystemProgram.transfer({
          fromPubkey: accountFrom.publicKey,
          toPubkey: accountTo.publicKey,
          lamports: 10,
        }),
      );

      const fee = await transaction.getEstimatedFee(connection);
      expect(fee).to.eq(5000);
    });
```

**Comment by acheroncrypto** [comment]
@iMrDJAi the first buffer is valid based on the schema you've defined in your initial post. The problem here is that the schema you've defined does not match [`SystemInstruction::Transfer`](https://github.com/solana-labs/solana/blob/8325b0f591624ce0649e6202d5512753832f3f43/sdk/program/src/system_instruction.rs#L232).

`SystemInstruction` uses 4 bytes discriminator to decide the variant and `SystemInstruction::Transfer` variant  carries `{ lamports: u64 }` as data.

Example working code:
```ts
class Payload {
  id = 2;
  lamports: BN;
  constructor({ lamports }: { lamports: BN }) {
    this.lamports = lamports;
  }
}

const schema = new Map([
  [
    Payload,
    {
      kind: "struct",
      fields: [
        ["id", "u32"],
        ["lamports", "u64"],
      ],
    },
  ],
]);

const transfer = new Payload({
  lamports: new BN(web3.LAMPORTS_PER_SOL * 0.42),
});

const data = Buffer.from(borsh.serialize(schema, transfer));
console.log(data); // <Buffer 02 00 00 00 00 b1 08 19 00 00 00 00>
```
Note that I've hardcoded the discriminator as **2** here for demonstration purposes but you can also make it flexible if you also want to include other variants of `SystemInstruction`.

**Comment by iMrDJAi** [comment]
@katopz

1. `recipientAddress` is of `web3.PublicKey` type.
2. `SystemProgram.transfer()` work as expected with `parseInt`, but I'll use a proper math library to ensure precision.
3. What I'm trying to achieve is replicating `SystemProgram.transfer()` with the low level `web3.TransactionInstruction()`, my only issue is serializing the `data` payload:

```ts
new web3.TransactionInstruction({
    keys: [
      { pubkey: senderKeypair.publicKey, isSigner: true, isWritable: true },
      { pubkey: recipientAddress, isSigner: false, isWritable: true }
    ],
    programId: web3.SystemProgram.programId,
    data // Should include amount
})
```

**Comment by iMrDJAi** [comment]
@acheroncrypto I tested the schema you provided, and it works. It looks like that the [tutorial](https://solanacookbook.com/guides/serialization.html#how-to-serialize-instruction-data-on-the-client) I've followed provided incorrect information about the schema format.

Thank you so much for your support everyone.
