### ISSUE TITLE
Request clockwork-sdk 2.0.15 and @clockwork-xyz/sdk 0.3.0

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#131]
Requesting update to `clockwork-sdk` 2.0.15 and support for `@clockwork-xyz/sdk` 0.3.0

Goal is to build/deploy this clockwork counter [example](https://github.com/clockwork-xyz/examples/tree/main/2-counter) from this [tutorial](https://github.com/clockwork-xyz/docs/blob/main/developers/guides/1-counter.md) and use `@clockwork-xyz/sdk` in client.ts and anchor.test.ts

Thanks for building and maintaining solpg!

**Comment by acheroncrypto** [comment]
Added in https://github.com/solana-playground/solana-playground/commit/b41f41ce87702af0d8a41d39c2a15101874c7038

By the way type resolution should be much faster now, also added type support for metaplex sdk. These packages are only loaded if they are being used so we should be able to support all of the packages people might use.
