### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by 5pecter** [solana-playground/solana-playground#143]
when i build and tried to deploy a program in solana playground it is building the program correctly but the building process is not working
![Screenshot from 2023-06-22 09-08-31](https://github.com/solana-playground/solana-playground/assets/137094877/0186594b-a200-41d7-a76a-9f8805bccd16)

it also tells me to put a issue in the github . so i posted a issue here . pls help me with this

**Comment by acheroncrypto** [comment]
I wasn't able to reproduce the issue. Could you share which endpoint you are using to deploy and the console logs(F12)?

**Comment by 5pecter** [comment]
![Screenshot from 2023-06-22 22-46-46](https://github.com/solana-playground/solana-playground/assets/137094877/2cbe9f1e-9f49-428b-9267-191b6be1b008)

**Comment by Nelo0** [comment]
I was having the same issue, it occurred to me when I tried to update a deployed program.

To fix it I made a new program key-pair for the program that I was up loading
<img width="363" alt="Screenshot 2023-07-17 at 22 43 41" src="https://github.com/solana-playground/solana-playground/assets/83479019/ad2e1ca7-b907-4560-8ed0-aeb0d80b6378">
