### ISSUE TITLE
Seed generation force the first seed to be string

### ISSUE THREAD

**Issue by JuanMarchetto** [solana-playground/solana-playground#150]
In the "TEST" view if you select "from seed" in an address it give you a first seed which is string and you can't change that or delete it.

Proposal:
- The type of that seed should be able to change
- The seed should be posible to remove

**Comment by acheroncrypto** [comment]
Agreed, there is a lot of potential improvements in test UI.

> Proposal:
> 
> * The type of that seed should be able to change
> * The seed should be posible to remove

This was actually implemented in https://github.com/solana-playground/solana-playground/pull/113 but it wasn't merged due to the other things that the PR had.

**Comment by acheroncrypto** [comment]
Implemented in https://github.com/solana-playground/solana-playground/commit/dad9d436a6c08de03972b240009f29f686c3019b

The first seed type no longer defaults to `string` and you can also delete it:

![generate-from-seed-select](https://github.com/solana-playground/solana-playground/assets/98934430/cd0d5f7d-960f-46c1-ac38-2e8b26941e20)

You can also edit any individual seed selection:

![generate-from-seed-edit](https://github.com/solana-playground/solana-playground/assets/98934430/e93167c0-defc-439b-987c-46b5ab19eb33)

Thanks for the proposal!
