### ISSUE TITLE
Switchboard v3 crate

### ISSUE THREAD

**Issue by MetamizeMe** [solana-playground/solana-playground#152]
Vrf v2 is already deprecated but will continue maintenance for the forseable future. All new work is on v3 randomness which is much cheaper and more efficient.

To be able to use v3 this crate would have to be added: "switchboard-solana = "0.28.12""

My suggestion would be to leave the "switchboard-v2 | 0.4.0" crate and add the "switchboard-solana = "0.28.12"" crate to support both and users have the time to make the transition to v3.

**Comment by acheroncrypto** [comment]
[`switchboard-solana 0.28.18`](https://crates.io/crates/switchboard-solana/0.28.18) is now [supported](https://github.com/solana-playground/solana-playground/blob/c71e1a03e067794ed2d243e8784ef21f2f30ef26/supported-crates.json#L21), thanks for the request.
