### ISSUE TITLE
Deployment failed without any reason

### ISSUE THREAD

**Issue by ZivxYoung** [solana-playground/solana-playground#153]
![image](https://github.com/solana-playground/solana-playground/assets/133080617/f9a0695e-825a-4ef2-bd33-0944cd21eb4d)
![image](https://github.com/solana-playground/solana-playground/assets/133080617/571015a6-0765-4ee0-8d90-f1f3ed19f5b4)

I was new to Solana Programming after the program build successfully, when I clicked deploy it failed due to this error, I am using Devnet. is anyone know how to fix this?

**Comment by acheroncrypto** [comment]
Did it fail at the end? Would be great if you could you share the logs in the browser console. You can open it with `Ctrl+Shift+I` or `F12` or right click -> Inspect -> Console.

**Comment by ZivxYoung** [comment]
![image](https://github.com/solana-playground/solana-playground/assets/133080617/7b68adac-d791-4d63-a04d-05ed5cd5c768)

owh okay I opened the console, I noticed that it said "Failed to load resource: net::ERR_NAME_NOT_RESOLVED"
is it the code error ? but the code has already build successfully

**Comment by acheroncrypto** [comment]
The error is `invalid account data for instruction` which I'm guessing the error only failed at the last instruction. This is most likely because there is a connection error to the devnet RPC(which can be seen from the screenshot as well). Are you able to reproduce this issue for example after refreshing the page or creating a new workspace with the same program?

**Comment by ZivxYoung** [comment]
not sure how to reproduce but I m still having the same issue and my code is just basic program following turorial since I m new to solana programming, but below is my code:
use anchor_lang::prelude::*;
use anchor_lang::solana_program::entrypoint::ProgramResult;
use anchor_spl::token::{self, Token};
use std::mem::size_of;

//pub mod constant;
//pub mod states;

// // crate = npm (like a package)
//use crate::{constant::*, states::*};

// our program's publickey (will update automatically when build project)
declare_id!("5eVMMxzdFuZKw3Yz5nQ3d5sf3cZbwpo4RrMzhzCAakrV");

// define program
pub mod funding_platform {
    use super::*;

    pub fn accept_payment(ctx: Context<PayerContext>, data: u64) -> ProgramResult {
        // ctx is type (Context<PayerContext>) PayerContext comes from below

        // see usecase (Entry PAYMENT FOR APP)
        let payer_wallet = &mut ctx.accounts.payer_wallet;
        payer_wallet.wallet = ctx.accounts.authority.key(); // value of the PayerAccount, .wallet comes from payerAccount Struct

        let ix = anchor_lang::solana_program::system_instruction::transfer(
            &ctx.accounts.authority.key(),
            &ctx.accounts.receiver.key(),
            10000000,
        ); // how much should pay

        anchor_lang::solana_program::program::invoke(
            &ix,
            &[
                ctx.accounts.authority.to_account_info(),
                ctx.accounts.receiver.to_account_info(),
            ],
        )
    }
}

#[derive(Accounts)]
pub struct PayerContext<'info> {
    #[account(
        init,
        seeds = [b"payer".as_ref(), authority.key().as_ref()],       // generate unique hash based on the seed
        bump,                                                       // bump will increment the hash to create unique (like id += 1)
        payer = authority,                                          // whos paying for the smart contract => authority
        space = size_of::<PayerAccount>()+8
        )] // in Rust, is a must to know the space
    pub payer_wallet: Account<'info, PayerAccount>,

    #[account(mut)]
    pub receiver: AccountInfo<'info>,

    // Authority (signer who paid transaction fee, authority = signer)// let it become mut, this authority can change (mut = not constant)
    #[account(mut)]
    pub authority: Signer<'info>,

    pub system_program: UncheckedAccount<'info>,

    // Token Program
    #[account(constraint = token_program.key == &token::ID)]
    pub token_program: Program<'info, Token>,

    // Clock to save time
    pub clock: Sysvar<'info, Clock>,
}

#[account]
pub struct PayerAccount {
    pub wallet: Pubkey,
}

**Comment by acheroncrypto** [comment]
This is because the program module doesn't have a `program` attribute so the program is not being created.

Instead of
```rs
// define program
pub mod funding_platform {
```

should be
```rs
// define program
#[program]
pub mod funding_platform {
```

**Comment by ZivxYoung** [comment]
i think it fix the issue, alright Thank you so very much!!
