### ISSUE TITLE
How can i get rid of this error -> program id mismatch

### ISSUE THREAD

**Issue by pooriagg** [solana-playground/solana-playground#155]
![Screenshot 2023-10-13 114917](https://github.com/solana-playground/solana-playground/assets/104061307/6310b17c-dd99-42e6-8689-169e9ccfdd5d)

I have checked all program ids but they are all correct !

**Comment by acheroncrypto** [comment]
This can happen if you've changed the program id but haven't rebuilt the program before deploying again.

**Comment by pooriagg** [comment]
Thx a lot problem solved.
