### ISSUE TITLE
Add a new section in Solana native program development section to export program's bytecode file (.so) .

### ISSUE THREAD

**Issue by pooriagg** [solana-playground/solana-playground#156]
Please add a new section in Solana native program development section to export program's bytecode file (.so) .

**Comment by acheroncrypto** [comment]
We can add this. Question is, whether to export the deployed program on-chain or just the built program or even both?

**Comment by pooriagg** [comment]
I think just build program (.so) is enough.

**Comment by acheroncrypto** [comment]
Why close? This hasn't been added yet.

**Comment by acheroncrypto** [comment]
Added in https://github.com/solana-playground/solana-playground/commit/dcfecd7a5662e1f5a23f4bc225660ac3672cb99e
