### ISSUE TITLE
How to deploy the Solana program with Solana js SDK?  

### ISSUE THREAD

**Issue by liushooter** [solana-playground/solana-playground#160]
hi, i submited the same issue：https://github.com/solana-labs/solana/issues/33939 

I accidentally discovered that the solana-playground provides similar functionality. 

I tried using the `BpfLoaderUpgradeable.createBuffer` method, but it didn't work for me.

The following is the relevant code:

https://github.com/666pulse/solana-nft-anchor/tree/main/deploy

**Comment by acheroncrypto** [comment]
Looks like you've copied the deployment code from the [vscode extension](https://github.com/solana-playground/solana-playground/tree/master/vscode), you don't need to manually call anything as the full deployment code is already in your repository [here](https://github.com/666pulse/solana-nft-anchor/blob/db56f17905c4422265ed20289b227234e655ffa5/deploy/deploy.ts) which uses `BpfLoaderUpgradeable.createBuffer` [here](https://github.com/666pulse/solana-nft-anchor/blob/db56f17905c4422265ed20289b227234e655ffa5/deploy/deploy.ts#L75).

Might release an SDK for handling deployment in JS if there is a demand for it.

**Comment by liushooter** [comment]
👍 
About when will the JS SDK for handling deployment be released？

**Comment by acheroncrypto** [comment]
Most likely when we split up the massive `client` directory into multiple packages but unfortunately, I can't give an ETA. I haven't fully checked your repo but it should work because we already use it which means you don't have to wait for the package release.
