### ISSUE TITLE
Request to update anchor-lang and anchor-spl to 0.29.0

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#165]
Would it be possible to update Solana Playground  version of anchor-lang and anchor-spl to 0.29.0 in order to use the new syntax for bumps, transferring lamports, and accessing mpl_token_metadata through anchor-spl?

**Comment by acheroncrypto** [comment]
Thanks, yes it's possible but there are some issues with this update currently so it will take some time.

**Comment by Mreparepas** [comment]
Update anchor

**Comment by acheroncrypto** [comment]
Updated in https://github.com/solana-playground/solana-playground/commit/22d0028294b2e7ac68e126113d334369912616a4

Sorry for the delay!
