### ISSUE TITLE
How to make provider.wallet in test files compatible with Solana Playground wallet when importing from Github

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#166]
The ability to import programs into Playground directly from Github is an awesome feature!

Sometimes in the test file of a local project I use the `provider.wallet` to sign for transactions with `wallet.payer`. 
However, when using Solana Playground, the syntax needs to be changed to `wallet.keypair`.
```
const wallet = provider.wallet as anchor.Wallet;
 ....
const transactionSignature = await sendAndConfirmTransaction(
  connection,
  transaction,
  [wallet.payer] // `wallet.keypair` when using playground
);
```
In this [example](https://beta.solpg.io/https://github.com/solana-developers/anchor-examples/tree/main/account-types/Signer), if we import the project then `build` and `deploy` on Solpg, the test file still needs to be updated. Otherwise, the test using `wallet.payer` returns:
```
TypeError: Cannot read properties of undefined (reading 'publicKey')
```

Is there a way to make the `provider.wallet` in local test files directly compatible to use in Solana Playground?

**Comment by acheroncrypto** [comment]
> Is there a way to make the `provider.wallet` in local test files directly compatible to use in Solana Playground?

Yes, definitely — we already have custom implementations for `anchor.AnchorProvider.env()` and `anchor.workspace`, can also add `provider.wallet`.

**Comment by acheroncrypto** [comment]
Added in https://github.com/solana-playground/solana-playground/commit/4282127c07516c6328f1b370f5076d0f1dc72bce
