### ISSUE TITLE
how to provide a input for Vec[publicKey] in solana playground

### ISSUE THREAD

**Issue by tpkeeper** [solana-playground/solana-playground#169]
how to provide a input for Vec[publicKey] in solana playground?
like this ["3Ue6jwMfqYaxw4NJFYTW8PkrXwdn9foei4h7mxuqPuZY","3Ue6jwMfqYaxw4NJFYTW8PkrXwdn9foei4h7mxuqPuZY"] ?

**Comment by acheroncrypto** [comment]
Test UI is being updated right now to support more complex data inputs like this — in fact, this is already implemented in `master` branch and will be deployed (most likely) next week. You'll be able to input like you've shared above, currently I don't think it works in the live version.
