### ISSUE TITLE
Add support for mpl-token-auth-rules

### ISSUE THREAD

**Issue by posinaga-demo** [solana-playground/solana-playground#171]
Please add support for https://crates.io/crates/mpl-token-auth-rules
Version is not that important.

**Comment by acheroncrypto** [comment]
Thanks, will add soon.

**Comment by acheroncrypto** [comment]
Thanks for the suggestion, added in https://github.com/solana-playground/solana-playground/commit/22d0028294b2e7ac68e126113d334369912616a4

https://github.com/solana-playground/solana-playground/blob/22d0028294b2e7ac68e126113d334369912616a4/supported-crates.json#L11
