### ISSUE TITLE
Add support for serde

### ISSUE THREAD

**Issue by posinaga-demo** [solana-playground/solana-playground#172]
Please add support for https://crates.io/crates/serde
Version is not that important.

**Comment by acheroncrypto** [comment]
Thanks for the suggestion, `serde` is often not used on-chain but added it in https://github.com/solana-playground/solana-playground/commit/22d0028294b2e7ac68e126113d334369912616a4

https://github.com/solana-playground/solana-playground/blob/22d0028294b2e7ac68e126113d334369912616a4/supported-crates.json#L17
