### ISSUE TITLE
Non-awaited async function errors don't get caught

### ISSUE THREAD

**Issue by acheroncrypto** [solana-playground/solana-playground#177]
### Problem

The following client code gets caught:

```ts
function throwError() {
  throw new Error("Failure!");
}

throwError();
```

```ts
async function throwError() {
  throw new Error("Failure!");
}

await throwError();
```

and prints to terminal correctly:

```
$ run
Running client...
  client.ts:
    Uncaught error: Failure!
```

but the error doesn't get caught if it's an async function without an `await` call:

```ts
async function throwError() {
  throw new Error("Failure!");
}

throwError();
```

### Solution

Catch the error from the `iframe` and print it in the terminal similar to how the other errors are handled.

**Comment by vinaybhamre** [comment]
Hey @acheroncrypto, 
Can I work on this?

**Comment by acheroncrypto** [comment]
Yeah, sure!

**Comment by Tgcohce** [comment]
We can create a global event listener that looks for unhandled promise rejection that could solve this issue:

```
window.addEventListener('unhandledrejection', (event) => {
  console.error('Unhandled promise rejection:', event.reason);
});
```

**Comment by Tgcohce** [comment]
To print in the iframe like other errors, we can do something like:
```
window.addEventListener('unhandledrejection', function(event) {
  parent.postMessage({
    type: 'error',
    message: `Unhandled promise rejection: ${event.data.message}`
  }, '*');
});
```

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/solana-playground/solana-playground/commit/7e4e09ff6719bf6fd54ef0ebf4026bf8479dbe33
