### ISSUE TITLE
UI & UX improvement to provide `Deploy Program Tx Hash` and `Upgrade Program Tx Hash`

### ISSUE THREAD

**Issue by mryalamanchi** [solana-playground/solana-playground#18]
Currently, the UI Console only displays `Deployment Successful` once the program is deployed 
and `Deploy Program Tx Hash:`  in the Developer Console.

It will be great to have the Tx Hash displayed on the UI Console as well,
making it easy to spot the Tx on the explorer for the dev.

**Comment by acheroncrypto** [comment]
The tx hash is pretty long and takes up a lot of space for the people who don't want to see it. What do you think about making a toast notification with a clickable explorer link instead?

**Comment by mryalamanchi** [comment]
Damn! You are a true chad giga brain UX guy!

I suggest then we do the same for `Upgrade Program Tx hash` as well. 
Since, the deploy function returns the txhash.

What do you think?

What do you think?

**Comment by acheroncrypto** [comment]
Sounds good! Might as well add the testing tx as well as it currently prints the tx hash to the terminal.

**Comment by acheroncrypto** [comment]
Added it in aed7153d99b57cb73b39eb5189b63483ff6c9071 sir, let me know if you like it.

**Comment by mryalamanchi** [comment]
Good thought on adding it for airdrop as well!

It's perfect! 
Thank you.

Closing the issue.
