### ISSUE TITLE
Error when testing with seeds

### ISSUE THREAD

**Issue by lostintime101** [solana-playground/solana-playground#187]
![err](https://github.com/solana-playground/solana-playground/assets/92709487/cbee63c6-ed75-4de2-bb28-0d68fd3678d7)

https://github.com/solana-playground/solana-playground/assets/92709487/3d1b718f-8ee4-4e42-8c05-d2e386d425eb

Same error across separate devices/OS: Linux Firefox & Windows Chrome

**Comment by acheroncrypto** [comment]
The website was updated an hour ago so this was a new bug, it should now be fixed with 59d36a82580b8f4a31fdfc6b259515b3259354f0. Please refresh the page to fetch the newest version.

Thanks for creating the issue, especially with a video example.

**Comment by lostintime101** [comment]
It's fixed. Great job!
