### ISSUE TITLE
Support crates spl-token

### ISSUE THREAD

**Issue by duythien0912** [solana-playground/solana-playground#19]
Hi thanks for awesome work.

Can you help to add spl-token crate 😇.

Thanks you 🙌

**Comment by acheroncrypto** [comment]
Native Solana program support will be added soon, you can use [anchor-spl](https://docs.rs/anchor-spl/0.24.2/anchor_spl/token/index.html) crate in the meantime it's basically a wrapper for spl-token crate

**Comment by acheroncrypto** [comment]
`spl-token` crate is now supported. You can see full list of available crates [here](https://github.com/solana-playground/solana-playground/blob/master/README.md).
