### ISSUE TITLE
Running yarn setup gives error

### ISSUE THREAD

**Issue by krishhh16** [solana-playground/solana-playground#219]
![Screenshot 2024-04-01 200916](https://github.com/solana-playground/solana-playground/assets/148282517/8174baf6-a8eb-4da1-8298-79cc9a2c43de)

I tried to git clone into the repository for contribution purposes, and tried every step for running it locally, but got this error as shown in the screenshot

**Comment by acheroncrypto** [comment]
It's most likely because you have space in your path `gh repo`. Removing it should make it work.
