### ISSUE TITLE
[Feature Request] Code snippet sharing

### ISSUE THREAD

**Issue by mryalamanchi** [solana-playground/solana-playground#22]
Just riffing with the idea of code snippet sharing on SolPg.

- Share code snippets with a shortened URL, makes sharing small PoCs easier for devs.
- Have an option to import the code from a git repo like GitHub (May cause an issue with Anchor.toml, Cargo.toml file imports)
- Have an option to export the files from SolPg into a compressed package.

**Comment by mryalamanchi** [comment]
I understand that this feature is a complex one to do single-handedly, 
kindly suggest where you may need help if you were to build this out!

Devs should be happy to contribute!

**Comment by acheroncrypto** [comment]
Yes, all of these features are needed for better experience.

> Share code snippets with a shortened URL, makes sharing small PoCs easier for devs.

Added this recently, haven't announced yet but you can use the feature currently. [Example](https://beta.solpg.io/626da949be353abcd4040401). There is a share button in explorer page.

> I understand that this feature is a complex one to do single-handedly,
kindly suggest where you may need help if you were to build this out!

I appreciate any help and you can work on this if you'd like, but this features are probably too difficult for new people to implement. I will be opening some easier issues for people to implement if they want to contribute.

**Comment by mryalamanchi** [comment]
I totally missed the share feature. It works!

**Comment by acheroncrypto** [comment]
> Share code snippets with a shortened URL, makes sharing small PoCs easier for devs.
Have an option to import the code from a git repo like GitHub (May cause an issue with Anchor.toml, Cargo.toml file imports)
Have an option to export the files from SolPg into a compressed package.

Closing this as all 3 of these requests have been implemented.
