### ISSUE TITLE
Allow `.so` file import

### ISSUE THREAD

**Issue by acheroncrypto** [solana-playground/solana-playground#24]
We should allow users to import their `.so` file and deploy from playground because many people have deployment problems with the solana-cli.

**Comment by mryalamanchi** [comment]
Sould the frontend be able to verify whether .so file is of BPF arch and ELF format or we want it to be optimistic?

**Comment by acheroncrypto** [comment]
I think it's much better to be optimistic then to implement a verifier(don't know if something like this in js exists)

**Comment by acheroncrypto** [comment]
Added this functionality in 8e5828f8645a5ec8b7c2e4f2d40aa2a5fbb5a1eb 64a789e0e8c113628ad59af642a298799dd89c24.
