### ISSUE TITLE
Too many airdrops error

### ISSUE THREAD

**Issue by Tgcohce** [solana-playground/solana-playground#262]
The issue I have here is the following error:

**Process error: Client error: You have requested too many airdrops. Wait 24 hours for a refill.**

Even if you just enter the playground in the browser and do "connect", and right after "solana airdrop 2". This is the error I get, I have tried this with 2 different computers in 2 different locations there seems to be some type of an issue when it comes to requesting airdrop as it will happen even if it is your first time entering the site, so far i have not been able to get any type of airdrop. I am sure it would be better to just play around with Solana playground on my local machine, however I believe that misses the point of having an accessible browser based Solana IDE. If there is another issue related to this feel free to close it and direct me there. Thank you.

**Comment by acheroncrypto** [comment]
> Even if you just enter the playground in the browser and do "connect", and right after "solana airdrop 2". This is the error I get, I have tried this with 2 different computers in 2 different locations there seems to be some type of an issue when it comes to requesting airdrop as it will happen even if it is your first time entering the site, so far i have not been able to get any type of airdrop

You might get this error even if you haven't manually requested airdrop yourself because the playground automatically requests airdrop if you don't have enough funds. Airdrops are also heavily rate-limited unfortunately.

> I am sure it would be better to just play around with Solana playground on my local machine, however I believe that misses the point of having an accessible browser based Solana IDE.

If you can just run `solana-test-validator`, you can connect to your local validator from playground which doesn't have these limitations.

> If there is another issue related to this feel free to close it and direct me there.

We've just been talking about airdrops in https://github.com/solana-playground/solana-playground/issues/261

**Comment by Tgcohce** [comment]
yeah but even if it autorequests it, it does not show up. Where is the code related?

**Comment by Tgcohce** [comment]
Nevermind I just see in the issue you listed that it is being worked on, I will move it there.
