### ISSUE TITLE
[BUG] import component does not re-renders on import

### ISSUE THREAD

**Issue by rishipatel9** [solana-playground/solana-playground#275]
after importing a project the project is not visible, after changing tha tab the projects are visible

**Comment by acheroncrypto** [comment]
How do you reproduce this? Everything seems to re-render correctly when I try importing.

**Comment by rishipatel9** [comment]
https://github.com/user-attachments/assets/45e5ddb9-dc61-4ce1-aa5b-213ba8174fd4

**Comment by acheroncrypto** [comment]
Thanks, fixed in https://github.com/solana-playground/solana-playground/commit/9c44b0ba0e2c6863fef9182eeced37667871dd6f
