### ISSUE TITLE
`a.tf.onDidChangePk` error when loading playground page

### ISSUE THREAD

**Issue by Woody4618** [solana-playground/solana-playground#279]
I cant use playground at the moment. No code is loaded and i'm getting this error: 

<img width="957" alt="image" src="https://github.com/user-attachments/assets/6ee1725c-dd3e-4e02-916f-68b8f0035fea">

These are the logs: 

```
`Removing unpermitted intrinsics
7123.80ef2131.chunk.js:2 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
e._parseColor @ 7123.80ef2131.chunk.js:2
e.setTheme @ 7123.80ef2131.chunk.js:2
t.open @ 7123.80ef2131.chunk.js:2
e.open @ 7123.80ef2131.chunk.js:2
open @ 1602.d22b3f46.chunk.js:953
(anonymous) @ 1602.d22b3f46.chunk.js:109
Fu @ main.9142e291.js:2
t.unstable_runWithPriority @ main.9142e291.js:2
Yo @ main.9142e291.js:2
Bu @ main.9142e291.js:2
yu @ main.9142e291.js:2
(anonymous) @ main.9142e291.js:2
t.unstable_runWithPriority @ main.9142e291.js:2
Yo @ main.9142e291.js:2
Go @ main.9142e291.js:2
Qo @ main.9142e291.js:2
ze @ main.9142e291.js:2
(anonymous) @ main.9142e291.js:2
Br @ main.9142e291.js:2
Jt @ main.9142e291.js:2
Zt @ main.9142e291.js:2Understand this warning
1602.d22b3f46.chunk.js:953 Couldn't setup files: ENOENT: /local-hello
1602.d22b3f46.chunk.js:130 MAIN VIEW ERROR: Already exists
main.9142e291.js:2 TypeError: a.tf.onDidChangePk is not a function
    at 3359.89300b16.chunk.js:57:2111
    at Fu (main.9142e291.js:2:219276)
    at t.unstable_runWithPriority (main.9142e291.js:2:246198)
    at Yo (main.9142e291.js:2:159595)
    at Bu (main.9142e291.js:2:218737)
    at main.9142e291.js:2:218648
    at z (main.9142e291.js:2:245257)
    at w.port1.onmessage (main.9142e291.js:2:243979)
cl @ main.9142e291.js:2
n.payload @ main.9142e291.js:2
ha @ main.9142e291.js:2
Vi @ main.9142e291.js:2
ql @ main.9142e291.js:2
Au @ main.9142e291.js:2
Ru @ main.9142e291.js:2
Tu @ main.9142e291.js:2
yu @ main.9142e291.js:2
(anonymous) @ main.9142e291.js:2
t.unstable_runWithPriority @ main.9142e291.js:2
Yo @ main.9142e291.js:2
Go @ main.9142e291.js:2
Qo @ main.9142e291.js:2
Fu @ main.9142e291.js:2
t.unstable_runWithPriority @ main.9142e291.js:2
Yo @ main.9142e291.js:2
Bu @ main.9142e291.js:2
(anonymous) @ main.9142e291.js:2
z @ main.9142e291.js:2
w.port1.onmessage @ main.9142e291.js:2Understand this error`
```

Using chrome on mac. It works fine in an incognito window.

**Comment by acheroncrypto** [comment]
Are you able to reproduce it locally? And what happens if you start from https://beta.solpg.io/programs

**Comment by Woody4618** [comment]
When i got to https://beta.solpg.io/programs looks like this: 
<img width="1910" alt="image" src="https://github.com/user-attachments/assets/def81098-e219-4b8c-a72d-3bbaa1dd8529">

Running it locally on http://localhost:3000/ works just fine. 
Also all works fine when i load it in another profile or in incognito mode.

**Comment by acheroncrypto** [comment]
It looks like the data that's saved to IndexedDB somehow got corrupted, which makes initialization fail:

https://github.com/solana-playground/solana-playground/blob/68569dd9e53357e69ae2ef7caaed2ae8819dd08a/client/src/utils/pg/explorer/explorer.ts#L1094

We also have a way to recover from errors like this one, but it doesn't seem to work for you:

https://github.com/solana-playground/solana-playground/blob/68569dd9e53357e69ae2ef7caaed2ae8819dd08a/client/src/utils/pg/explorer/explorer.ts#L1096-L1117

You'd have to copy the IndexedDB data you have on beta.solpg.io to localhost:3000 to be able to debug this properly.

**Comment by Woody4618** [comment]
I managed to recover it by loading one of the tutorials. Looks like my "local-hello" workspace got somehow corrupted. But not that one also works again. strange
