### ISSUE TITLE
Make explorer collapsible

### ISSUE THREAD

**Issue by xTeKc** [solana-playground/solana-playground#28]
Add the ability to optionally collapse the entire explorer by clicking the double paper icon.
![double-paper](https://user-images.githubusercontent.com/81730792/169634297-408ce974-02f9-47f2-b7e1-410fa7e90e60.png)

**Comment by acheroncrypto** [comment]
Added this on e39e101d3d1169c69a7c79ffdcf4bf03c2cf9d5f.
