### ISSUE TITLE
Local typescript imports

### ISSUE THREAD

**Issue by MitchPierias** [solana-playground/solana-playground#315]
I'm trying to modularize and refactor my typescript test and client files in the Web IDE by creating a simple utils file with my helpers and importing the functions where needed. I can't figure out how I might do this in the Web IDE and how you're handling the virtual project. Ideally we could create folders in the Client section or a dedicated `utils`, `functions`, `lib` or `src` folder is added so that we can create files and functions to share between tests and clients.

What I'm trying to do;

![image](https://github.com/user-attachments/assets/19786dc9-c2fa-459d-952e-1c7ae6f45ad2)

![image](https://github.com/user-attachments/assets/e56ff1f1-06c3-42dc-b4ac-31a76f5bb11f)

But the local import of my utils is not found.

Also, I like the globally available web3 and anchor modules, but couldn't find what the spl-token might be available under. Luckily that import did work.

### Edit:
I just noticed the message when trying to run the script anyway. Any idea when these are coming and is the documentation of the available global libraries and their naming?

![image](https://github.com/user-attachments/assets/e69ca1df-8986-4d8a-b34d-50e2c578a591)

**Comment by acheroncrypto** [comment]
Yeah, we directly run these scripts in your browser (without using any server etc), so features such as imports basically need to be implemented from scratch.

> I just noticed the message when trying to run the script anyway. Any idea when these are coming...

It would be great to support local imports, but I don't have enough time for it currently.

> ... and is the documentation of the available global libraries and their naming?

You can see all supported packages from [`supported-packages.json`](https://github.com/solana-playground/solana-playground/blob/7d2600af4b80ea13a18358d57fec592828b951c5/supported-packages.json).

Also, you can press `CTRL+Space` when you are inside a quote of an `import` statement to see which packages are importable.
