### ISSUE TITLE
AbiExample could not find `log` in the list of imported crates

### ISSUE THREAD

**Issue by katopz** [solana-playground/solana-playground#33]
I got this error in `vscode`
```
solana_frozen_abi_macro
proc_macro AbiExample
failed to resolve: could not find `log` in the list of imported crates
could not find `log` in the list of imported cratesrustc[E0433](https://doc.rust-lang.org/error-index.html#E0433)
conflicting implementations of trait `solana_frozen_abi::abi_example::AbiExample` for type `program::vote::authorized_voters::AuthorizedVoters`
conflicting implementation in crate `solana_frozen_abi`:
- impl<T> AbiExample for T;rustc[E0119](https://doc.rust-lang.org/error-index.html#E0119)
```

and also this error while build `solana-client`
```
fox:solana-client katopz$ cargo build
   Compiling rand v0.7.3
   Compiling zeroize v1.3.0
   Compiling sha2 v0.9.9
   Compiling borsh v0.9.3
   Compiling curve25519-dalek v3.2.1
   Compiling libsecp256k1 v0.6.0
   Compiling ed25519-dalek v1.0.1
   Compiling ed25519-dalek-bip32 v0.2.0
   Compiling solana-program v1.11.0
   Compiling solana-sdk v1.11.0
   Compiling solana-extra-wasm v1.11.0-alpha (/Users/katopz/git/katopz/solana-playground/wasm/utils/solana-extra)
error[E0433]: failed to resolve: could not find `log` in the list of imported crates
 --> utils/solana-extra/src/program/vote/authorized_voters.rs:7:72
  |
7 | #[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq, Clone, AbiExample)]
  |                                                                        ^^^^^^^^^^ could not find `log` in the list of imported crates
  |
  = note: this error originates in the derive macro `AbiExample` (in Nightly builds, run with -Z macro-backtrace for more info)
```

not sure what i miss, anyway what's rust version you have there?

**Comment by acheroncrypto** [comment]
The crates were meant to compile to `wasm32-unknown-unknown` so in order to build them you need
```bash
cargo build --target wasm32-unknown-unknown --release
```
or to get the full pkg
```bash
wasm-pack build
```
Might be good idea to make it compile with default target to make docs.rs builds successful though.

**Comment by katopz** [comment]
Oh, I surely miss that `target` . Thanks, btw after use
```
cargo build --target wasm32-unknown-unknown --release
```
 I still stuck at same error.

And for 
```
wasm-pack build
```
I got this error
```
Error: crate-type must be cdylib to compile to wasm32-unknown-unknown. Add the following to your Cargo.toml file:

[lib]
crate-type = ["cdylib", "rlib"]
```

Maybe only me 🤔

**Comment by acheroncrypto** [comment]
I wasn't able to reproduce the error with `rustc 1.61.0` and updated now to `1.62.0` with no problems.
```
cargo build --target wasm32-unknown-unknown --release
```
The crate is used as a replacement for `solana-client` so it's a helper crate, which means it's not useful on it's own. Can you try to build `solana-cli-wasm` which uses the `solana-client-wasm` crate and see if you have the same error?
```
[lib]
crate-type = ["cdylib", "rlib"]
```
I didn't add this to `solana-client` because this creates `.wasm` build for `solana-client` which is not useful.

**Comment by acheroncrypto** [comment]
One easy fix would be to add the `log` crate to `solana-extra-wasm`. Let me know if it works for you, happy to accept pr if it fixes it.

**Comment by katopz** [comment]
i'm on `rustc 1.62.0-nightly (e1b71feb5 2022-05-03)`

Same error for `solana-cli-wasm` 
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/97060/178793871-e44b7d80-f735-4002-9419-ff2361d41350.png">

Add `log = "0.4"` didn't help
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/97060/178793280-b96fac6a-3a02-4885-b951-60c084eb617b.png">

I think something wrong with my setup or my mac (never happen with other crates before). I will try with other setup and report back later.

BTW, nothing rush here so no worry!. Anyway I will leave this issue open in case someone hit the same wall.

Thanks for your assist!

**Comment by acheroncrypto** [comment]
Good news is that I was able to reproduce the exact error with your version
![image](https://user-images.githubusercontent.com/98934430/178840589-894d7910-231e-42b0-8cff-e5644fed1fdf.png)

![image](https://user-images.githubusercontent.com/98934430/178840634-05ef37ba-aea0-4597-8a59-d4bced835337.png)

And after adding `log`:

![image](https://user-images.githubusercontent.com/98934430/178840742-5f739098-c448-4512-ac43-17385096a48f.png)

removed `log` crate(shouldn't matter for wasm builds).

```bash
rustup override set stable
cargo clean
cargo build --target wasm32-unknown-unknown --release
```

and it compiles, at least for me. Specific version I'm using is `rustc 1.62.0 (a8314ef7d 2022-06-27)`

**Comment by katopz** [comment]
Aww snap!  Working now, I can't remember why i'm on `nightly` 🤔

Thanks for your time. I owe you once! 🦀
