### ISSUE TITLE
font on the slpg terminal is tripping can anybody tell me whats going on?

### ISSUE THREAD

**Issue by kudarukuni** [solana-playground/solana-playground#34]
![Screenshot 2022-07-12 192823](https://user-images.githubusercontent.com/52784179/178555735-b4712a38-b48e-45a2-9a58-29e2491bd896.png)

**Comment by acheroncrypto** [comment]
Did this happen after translation of the page by chrome?

**Comment by acheroncrypto** [comment]
The simple solution for this is to **not translate** the page. You can select show original from the chrome extension if it's translated by default.

I don't believe there is a way for xterm.js to detect external modifications to the terminal.

**Comment by kudarukuni** [comment]
> Did this happen after translation of the page by chrome?

my default browser lang in English plus GT never even suggest to translate anything. i think the bug is in the app, read the documentation and it did mention the app is still in beta mode

**Comment by acheroncrypto** [comment]
Seeing from the screenshot, some parts of your app has been modified externally most likely by translate extension. For example: there is no `EXPLORE` or `GROUND` in the source code of the app which exists on your screenshot. Try clicking the translate extension from top and choose something along the lines of "don't translate this page" or "show original".
