### ISSUE TITLE
Invalid Account Data for Instruction

### ISSUE THREAD

**Issue by murtazaali1999** [solana-playground/solana-playground#35]
failed to send transaction: Transaction simulation failed: Error processing Instruction 1: invalid account data for instruction

Its showing during deployment to devnet.

**Comment by acheroncrypto** [comment]
If you made sure you've built successfully before you deploy, can you please share your wallet address and the program id on devnet(if it exists)?

**Comment by murtazaali1999** [comment]
Sorry, Probably not passing the correct params. Didn't mean to keep it open for so long. Yatzee 💯
