### ISSUE TITLE
[Feature Request] UI to fetch account data

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#36]
I think the test UI would be even more useful if there was a way to fetch the account data from the deployed program and view it in the playground.

I think a way to do `program.account.newAccount.fetch(publicKey)` and `program.account.newAccount.all()` would add a huge amount of value. This would let us test an instruction and immediately see its effect on-chain. 

I expect the UI for this would allow selecting an account (parsed from the IDL), either selecting all or optionally entering a specific address, and it'd then display the fetched data as nicely formatted JSON.

**Comment by acheroncrypto** [comment]
Completely agree, testing section needs some improvement.

**Comment by mcintyre94** [comment]
Thanks @acheroncrypto! Could you assign this issue to me please? I'd like to contribute this :)
