### ISSUE TITLE
Could you share dev instructions?

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#37]
Would love to look at how I could contribute to this! 

Specific questions:

- Do you need to run the `wasm` things locally and how do you do so?
- I cloned the repo locally, in client ran `yarn` and then `yarn start`, and I'm getting some TS errors:

```
Compiled with problems:X

ERROR in src/components/Panels/Side/Right/Test/Function.tsx:62:5

TS2322: Type 'never[]' is not assignable to type 'KV'.
  Index signature for type 'string' is missing in type 'never[]'.
    60 |   const [txVals, setTxVals] = useState<TxVals>({
    61 |     name: ixs.name,
  > 62 |     additionalSigners: [],
       |     ^^^^^^^^^^^^^^^^^
    63 |   });
    64 |   const [errors, setErrors] = useState<{ [key: string]: number }>({});
    65 |   const [loading, setLoading] = useState(false);


ERROR in src/utils/pg/test.ts:298:54

TS2345: Argument of type '(string | number | PublicKey | Signer | BN)[]' is not assignable to parameter of type 'Signer[]'.
  Type 'string | number | PublicKey | Signer | BN' is not assignable to type 'Signer'.
    Type 'string' is not assignable to type 'Signer'.
    296 |     }
    297 |
  > 298 |     const txHash = await PgTx.send(tx, conn, wallet, additionalSigners);
        |                                                      ^^^^^^^^^^^^^^^^^
    299 |     return txHash;
    300 |   }
    301 | }
```

Is there something else I need to do/some specific config I could be missing to get it running locally? I'm using Node `v16.16.0` (latest LTS).

**Comment by acheroncrypto** [comment]
Thank you for your interest in contributing!

>Do you need to run the wasm things locally and how do you do so?

You don't need to do anything specific as the repo includes pre-built packages for easier builds locally. Running `yarn` would suffice.

>I cloned the repo locally, in client ran yarn and then yarn start, and I'm getting some TS errors:

Not sure how that error occurs for you but not for me even though we are using the same version. But if that's the only error it should be pretty easy to fix. PR for the fix is welcome.
