### ISSUE TITLE
Can we have support for the reqwest crate?

### ISSUE THREAD

**Issue by lbianlbian** [solana-playground/solana-playground#45]
Thanks for making solana-playground, it is super helpful, especially for people new to Rust and Solana development!

I want to try and make a GET call to an API inside of my solana program, and I see that I need reqwest in order to do that. I don't see reqwest as a supported crate in your list of supported crates.

I apologize if this is actually an unreasonable request, I am new to Rust and Solana and I am not sure what is possible.

**Comment by acheroncrypto** [comment]
Thank you!

We can't have support for `reqwest` as there is no internet access inside Solana programs. You can see what's restricted from [here](https://docs.solana.com/developing/on-chain-programs/developing-rust#restrictions) and any crate that makes use of these features are therefore not allowed.

No need to apologize, we are all learning!
