### ISSUE TITLE
[Feature Request] anchor-lang 0.25.0

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#46]
Could Solpg be updated to anchor-lang 0.25.0 to enable building with anchor realloc feature

https://docs.rs/anchor-lang/latest/anchor_lang/derive.Accounts.html
<img width="314" alt="image" src="https://user-images.githubusercontent.com/75003086/182952034-57ae2ecb-1bc3-404e-b9e1-86cb2a47aff7.png">

**Comment by acheroncrypto** [comment]
This will be supported in the next update(after the Hackathon) along with `anchor-debug` feature #43

**Comment by acheroncrypto** [comment]
Playground is now using `anchor-lang` 0.25.0
