### ISSUE TITLE
Add Bump Field in the Interface

### ISSUE THREAD

**Issue by murtazaali1999** [solana-playground/solana-playground#47]
Hi , Add a bump field in the interface, So it'll be easy to bump accounts. Cheers 🍺

**Comment by acheroncrypto** [comment]
`From seed` should be able to calculate the bump automatically, is there any other usecase I'm missing?

**Comment by murtazaali1999** [comment]
Umm...so how many instructions I pass in the instructions above the account, the single bump would handle it, without a target ?

**Comment by acheroncrypto** [comment]
You can pass `#[account(seed = ..., bump)]` without specifying the bump value. You can get the address `From seed` when testing in the UI and you won't need the bump. Is there an example where you need the bump?

**Comment by murtazaali1999** [comment]
Im trying to do this, I want to make PDA accounts with different u8 bump value to create accounts belonging to the same user.

**Comment by acheroncrypto** [comment]
> I want to make PDA accounts with different u8 bump value to create accounts belonging to the same user.

You should never do this. PDA calculation is extremely expensive, and essentially limited to maximum 2^8 accounts(realistically much less than that) and you need to try to get it with brute force and what's worse is there is no guarantee you will hit a PDA, that's why bumps exist in the first place.

Instead use something like:
```rs
#[derive(Accounts)]
#[instruction(id: u8)]
pub struct MyAccount<'info> {
    #[account(seed = [authority.key().as_ref(), &[id]], bump)]
    pub user: Account<'info, User>.
    pub authority: Signer<'info>
}
```

Also you can ask about this in [Solana Stackexchange](https://solana.stackexchange.com/).

**Comment by murtazaali1999** [comment]
When I do this and pass this in the creation of the account, e.g: string , pubkey and number , It says: 

The program could not deserialize the given instruction

**Comment by acheroncrypto** [comment]
Can you share the how you `init` the account? `#[account(init, ...)]` part.

**Comment by murtazaali1999** [comment]
#[instruction(user_bump: u8)]

    #[account(init, payer = user, space = 10000,seeds=[b"pool".as_ref(), user.key().as_ref(),&[user_bump]],bump)]

**Comment by acheroncrypto** [comment]
```rs
use anchor_lang::prelude::*;

declare_id!("11111111111111111111111111111111");

#[program]
mod my_program {
    use super::*;
    pub fn init(ctx: Context<MyContext>, id: u8) -> Result<()> {
        msg!("Initialized user {}'s account #{}", ctx.accounts.user.key(), id);
        Ok(())
    }
}

#[derive(Accounts)]
#[instruction(id: u8)]
pub struct MyContext<'info> {
    #[account(
        init,
        payer = user,
        space = 8,
        seeds = [
            b"pool",
            user.key().as_ref(),
            &[id]
        ]
        ,bump)
     ]
    pub my_account: Account<'info, MyAccount>,
    #[account(mut)]
    pub user: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[account]
#[derive(Default)]
pub struct MyAccount {}
```

Make sure you are using the correct seeds.
Seed 1: pool (string)
Seed 2: the address that signs the transaction (pubkey)
Seed 3: id (number)

And testing:
![image](https://user-images.githubusercontent.com/98934430/183117918-157142ac-f291-407d-951e-f7c393d16266.png)
