### ISSUE TITLE
Build error: Fail to fetch, when using Anchor realloc

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#56]
Unsure what the error means, copy/pasted over working code
Appreciate any pointers

![solpg-programid](https://user-images.githubusercontent.com/75003086/188331651-f136e5d2-c72c-45a8-94da-7352ded2c2d8.gif)

**Comment by acheroncrypto** [comment]
Seems like `anchor-syn` was still using `0.24.2` so `realloc` wasn't supported. Should be fixed now, thanks for reporting!
