### ISSUE TITLE
Unable to input struct in Solanapg

### ISSUE THREAD

**Issue by sarkarshubhanshuk** [solana-playground/solana-playground#59]
Hello,
I am new to Solana development. I am using Solana Playground IDE to implement the [Tic-Tac-Toe implementation guide](https://www.anchor-lang.com/docs/tic-tac-toe).
I have run the setupGame function and can fetch the game details using the address for the game.
I have also implemented the play function which takes game address key, player address key and tile input (tile is a struct implementation with row and column values in it). I am facing issue in inputting the struct value "{0,1}" into the play function and run the function as the second player. But I am able to run the play function as first player and "{}" value for Tile input.
Can you kindly help how should I input the tile struct value "{0,1}" into play function? 

Posting here as I do not see any other forum for discussion (hopefully that will change in future :))

Attaching screenshot of disabled button
![image](https://user-images.githubusercontent.com/8047794/192101098-c65bef2a-186e-4482-abc1-b60c34dac73f.png)

**Comment by acheroncrypto** [comment]
Structs are passed in as **JSON objects** like this:

![image](https://user-images.githubusercontent.com/98934430/192105061-3fb76b67-0a1c-44a1-8da6-8321b1256d8b.png)

Arguments are usually identical to the [Anchor Javascript Reference](https://www.anchor-lang.com/docs/javascript-anchor-types) or the JSON version of it.

**Also one quick tip**: You can import projects from Github directly by clicking the Github icon on the top left Projects section and inputting the program folder link https://github.com/coral-xyz/anchor/tree/master/docs/programs/tic-tac-toe/programs/tic-tac-toe

**Comment by acheroncrypto** [comment]
> Posting here as I do not see any other forum for discussion (hopefully that will change in future :))

You can ask questions like these in [Solana StackExchange](https://solana.stackexchange.com/)
