### ISSUE TITLE
Request enable Copy/Paste in SolPg terminal 

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#67]
Playing around with the new client and test features, which are awesome!
It appears I'm not able to copy/paste from the terminal. For example, trying to copy the output to see the program logs.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/75003086/197319052-c6b8231b-0cf3-4a42-af08-46794908c530.png">

**Comment by acheroncrypto** [comment]
Which keybinds are you using when trying to copy/paste? It is already enabled and should work with `Ctrl+Shift+C` and `Ctrl+Shift+V` (`Cmd` instead of `Ctrl` if you are using macOS). You can also right click to copy and paste.

**Comment by ZYJLiu** [comment]
oh got it, thanks!
Was trying to use `Ctrl + C` and `Ctrl + V`. Works with  `Ctrl+Shift+C`
