### ISSUE TITLE
need to update the seahorse version for writing Smart Contracts in Seahorse

### ISSUE THREAD

**Issue by saikishore222** [solana-playground/solana-playground#75]

**Comment by acheroncrypto** [comment]
It has been updated and deployed! Only issue is that local module imports are not yet implemented in playground. Everything else should work as expected.

**Comment by saikishore222** [comment]
Hey, @acheroncrypto  thanks for updating the seahorse version in Solpg .I hope you will update the new version of Seahorse 0.2.3

**Comment by acheroncrypto** [comment]
Unfortunately 0.2.3 doesn't work with WASM as of right now, need custom implementation to make it work. And as I mentioned in the previous post, this only effects local imports.

Let me know if you run into any problems!
