### ISSUE TITLE
Crate: clockwork-sdk

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#77]
[Clockwork](https://www.clockwork.xyz/) is an automation engine for Solana, that allows scheduling/triggering transactions.

One of the components is a Rust crate `clockwork-sdk` which Solana programs can use to make themselves compatible with clockwork. It'd be great if we could get support for this crate in the playground build environment.

Package: clockwork-sdk
Version: 1.3.5
docs.rs link: https://docs.rs/clockwork-sdk/1.3.5/

LMK if you need any more information to add it! :)

**Comment by acheroncrypto** [comment]
Playground now supports [clockwork-sdk](https://docs.rs/clockwork-sdk/1.13.12).
