### ISSUE TITLE
[Bug] All contracts imported to solpg went missing

### ISSUE THREAD

**Issue by SkyYap** [solana-playground/solana-playground#79]
Previously I have created and imported from GitHub several contracts. However today I opened the website and found out all the contracts went missing and I need to start from scratch.

**Comment by acheroncrypto** [comment]
Are you able to reproduce this? Did you also lose wallet information? I don't think this can happen unless your browser data has been deleted, everything is stored on your browser.

**Comment by SkyYap** [comment]
> Are you able to reproduce this? Did you also lose wallet information? I don't think this can happen unless your browser data has been deleted, everything is stored on your browser.

I think it is my browser data deleted. Thanks for your feedback.
