### ISSUE TITLE
Can not create keypair using fromSecretKey in client.

### ISSUE THREAD

**Issue by Woody4618** [solana-playground/solana-playground#82]
When running this in the ts client I get an error:

const keypair = web3.Keypair.fromSecretKey(
  Uint8Array.from([
    174, 47, 154, 16, 202, 193, 206, 113, 199, 190, 53, 133, 169, 175, 31, 56,
    222, 53, 138, 189, 224, 216, 117, 173, 10, 149, 53, 45, 73, 251, 237, 246,
    15, 185, 186, 82, 177, 240, 148, 69, 241, 227, 167, 80, 141, 89, 240, 121,
    121, 35, 172, 247, 68, 251, 226, 218, 48, 63, 176, 109, 168, 89, 238, 135,
  ])
);

Error:
Uncaught error: hexToBytes: expected string, got object.

Any idea why?

**Comment by acheroncrypto** [comment]
There seems to be a weird behaviour for the polyfill as mentioned in https://github.com/paulmillr/noble-ed25519/issues/58.

This is fixed in b282ae7a7bb4735554659a9c1a2958de4325e418.
