### ISSUE TITLE
Deployement Error

### ISSUE THREAD

**Issue by vijay-kesanakurthi** [solana-playground/solana-playground#87]
**failed to send transaction**: 
Transaction simulation failed: Error processing Instruction 0: account data too small for instruction

`let clock = clock::Clock::get()?;
    msg!("clock: {:#?}", clock);`

Program deployed successfully, when i remove the above  lines of code.

**It works  in localhost, problem with devnet.**

**Comment by acheroncrypto** [comment]
You might have missed to build before you deploy, are you able to reproduce this error on a new project? I've tried the code you've sent and didn't have any issues.

**Comment by vijay-kesanakurthi** [comment]
Sometimes works, but sometimes not. I have same issue with the client.ts script.

**Comment by acheroncrypto** [comment]
> I have same issue with the client.ts script.

That could mean there is a problem with the RPC endpoint. Can you try changing it from the settings?

**Comment by vijay-kesanakurthi** [comment]
Changing from devnet to localhost make it work when I encountered the error, but now it's working on the devnet.

Thanks for your assistance.
