### ISSUE TITLE
Add a way to configure a custom RPC url 

### ISSUE THREAD

**Issue by Woody4618** [solana-playground/solana-playground#88]
Currently all mainnet RPCs endpoints don't work. 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/5938789/204530281-172356f0-1282-472e-b72b-b3c611278cbc.png">

Would be nice to have a way to configure a custom URL so I could put in my quicknode RPC url.

**Comment by acheroncrypto** [comment]
Hmm interesting that they all don't work, you can set custom URL with `solana config set -u <RPC_ENDPOINT>`. Should probably make it more obvious in the UI.

**Comment by dhruvsol** [comment]
@acheroncrypto  is it a good idea to make a global context for the custom RPC to use in it and we can add a option in dropdown so if that option is selected the modal popups and there we can add the RPC

**Comment by dhruvsol** [comment]
I am up to make it

**Comment by acheroncrypto** [comment]
> @acheroncrypto is it a good idea to make a global context for the custom RPC to use in it and we can add a option in dropdown so if that option is selected the modal popups and there we can add the RPC

I think you can do exactly like you said except the global context part, you should just be able to use
```ts
PgTerminal.runCmdFromStr(`solana config set -u ${userInput}`)
```
on the modal.

> I am up to make it

Thank you, I'm assigning this to you then.

**Comment by dhruvsol** [comment]
Hey @acheroncrypto ,
have a look 
https://www.loom.com/share/2ecce78eb86648ab87d076a0e878577b

and if you want to try it then 
https://github.com/dhruvsol/solana-playground 
if you see any changes then let me know

**Comment by dhruvsol** [comment]
https://github.com/solana-playground/solana-playground/pull/97
