### ISSUE TITLE
When a shared project is viewed, it is not showing content in the file.

### ISSUE THREAD

**Issue by vijay-kesanakurthi** [solana-playground/solana-playground#91]
![image](https://user-images.githubusercontent.com/104449500/205266350-a9ab92fb-c018-47ed-adb7-df94b7f2e0ea.png)

**Comment by acheroncrypto** [comment]
Can you send the link? Also would like to know if you are able to reproduce this.

**Comment by vijay-kesanakurthi** [comment]
It shows when I click on any of the tabs. But by default, it does showing any file content like normal solpg.

# SOLPG
![image](https://user-images.githubusercontent.com/104449500/205487831-7369593d-7a32-40c7-bb17-a0643f5bb3df.png)

# Shared Link
![image](https://user-images.githubusercontent.com/104449500/205488007-3d01c590-b592-437c-837f-eb44ee68be24.png)

**Comment by vijay-kesanakurthi** [comment]
It would be good if the content in the file load by default like normal solpg.

**Comment by acheroncrypto** [comment]
Thank you for the report! This was kind of an edge case and is fixed in ea124389b6693152147c3938d08990328a623df4.
