### ISSUE TITLE
Crate: pyth-sdk-rs

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#94]
Pyth is a service that makes crypto/other price data available on-chain

One of the components is a Rust crate pyth-sdk-solana which Solana programs can use to access the data

Package: pyth-sdk-solana
Version: 0.6.1
docs.rs link: https://docs.rs/pyth-sdk-solana/0.6.1/

LMK if you need any more information to add it! :)

**Comment by acheroncrypto** [comment]
Playground now supports [pyth-sdk](https://docs.rs/pyth-sdk/0.7.0) [pyth-sdk-solana](https://docs.rs/pyth-sdk-solana/0.7.0).
